### ISSUE TITLE
Bug Affecting TailwindUI Components Using HeadlessUI and React

### ISSUE THREAD

**Issue by brettpalmberg** [tailwindlabs/tailwindui-issues#1137]
**What component (if applicable)**

Suspect this affects any TailwindUI components that make use of @headlessui/react@latest. Posting here for awareness related to TailwindUI. Original issue filed here: https://github.com/tailwindlabs/headlessui/issues/1085

**Describe the bug**
Components that depend on @headlessui/react@latest raise an error out of the box, do not render or build.

**To Reproduce**

This is a clean-slate repository, bootstrapped with create-react-app to demonstrate the bug. The app tries to render the headlessui Menu (Dropdown) example component: https://headlessui.dev/react/menu, resulting in the error shown in Screenshots.

**Expected behavior**
TailwindUI components using @headlessui/react build and render without error.

**Screenshots**

Error text copied in-lieu of screenshot for easy reading and copy/paste:

```
Compiled with problems:X

ERROR in ./node_modules/@headlessui/react/dist/index.esm.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@headlessui/react/dist/index.esm.js: Cannot read property 'originalPositionFor' of undefined
    at SourceMapTree.originalPositionFor (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@ampproject/remapping/dist/remapping.umd.js:159:27)
    at trace (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@ampproject/remapping/dist/remapping.umd.js:102:37)
    at EncodedSourceMapImpl.map (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:347:36)
    at TraceMap.map (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:430:31)
    at SourceMapTree.traceMappings (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@ampproject/remapping/dist/remapping.umd.js:85:34)
    at remapping (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@ampproject/remapping/dist/remapping.umd.js:258:36)
    at mergeSourceMap (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@babel/core/lib/transformation/file/merge-map.js:19:30)
    at generateCode (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@babel/core/lib/transformation/file/generate.js:72:39)
    at run (/Users/rdcrlbtp/Documents/projects/cumulus-ui-too/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)
```

**Browser/Device (if applicable)**
 - OS: [macOS Catalina]
 - Browser [chrome]
 - Version [97.0.4692.99]

**Additional context**
Thank you for building this product!

**Comment by brettpalmberg** [comment]
Resolved. See information in https://github.com/tailwindlabs/headlessui/issues/1085.
