### ISSUE TITLE
Salient Fails to Build (Node v18.6.0, NPM v8.13.2)

### ISSUE THREAD

**Issue by RobbieMcKinstry** [tailwindlabs/tailwindui-issues#1274]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/salient
- Component name: Salient

**Describe the bug**

Downloading a fresh version of Salient fails to build locally. It's able to build successfully in a Node buildpack (presumably running with a different version of Node).

It might help to publish supported Node versions either in the README or here:
<img width="1787" alt="Screen Shot 2022-07-23 at 3 59 12 PM" src="https://user-images.githubusercontent.com/4955075/180620987-9274c9f3-1abb-4f84-ab13-24d2b3cb12a6.png">

**To Reproduce**

1. Download Salient
2. Unzip the compressed download.
```bash
$ unzip salient.zip
```
3. Change directories into Salient.
```bash
$ cd salient
```
5. Following the directions in README.md, install the dependencies.
```bash
$ npm install

added 275 packages, and audited 276 packages in 5s

79 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
5. Build a static executable.
```bash
$ npm run build

> tailwindui-saas@0.1.0 build
> next build

warn  - You have enabled experimental features (newNextLinkBehavior, images) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Linting and checking validity of types...
info  - Creating an optimized production build...
Failed to compile.

./src/images/background-auth.jpg
TypeError: Failed to parse URL from /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.wasm
    at new Request (node:internal/deps/undici/undici:5423:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6219:25)
    at Object.fetch (node:internal/deps/undici/undici:7053:20)
    at fetch (node:internal/bootstrap/pre_execution:198:25)
    at instantiateAsync (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:424:28)
    at createWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:447:13)
    at /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:1480:19
    at Object.instantiateEmscriptenWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/emscripten-utils.js:15:12)
    at Object.dec (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/codecs.js:171:42)
    at Object.decodeBuffer (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/impl.js:52:31)

Import trace for requested module:
./src/components/AuthLayout.jsx
./src/pages/login.jsx

./src/images/background-call-to-action.jpg
TypeError: Failed to parse URL from /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.wasm
    at new Request (node:internal/deps/undici/undici:5423:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6219:25)
    at Object.fetch (node:internal/deps/undici/undici:7053:20)
    at fetch (node:internal/bootstrap/pre_execution:198:25)
    at instantiateAsync (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:424:28)
    at createWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:447:13)
    at /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:1480:19
    at Object.instantiateEmscriptenWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/emscripten-utils.js:15:12)
    at Object.dec (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/codecs.js:171:42)
    at Object.decodeBuffer (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/impl.js:52:31)

Import trace for requested module:
./src/components/CallToAction.jsx
./src/pages/index.jsx

./src/images/background-faqs.jpg
TypeError: Failed to parse URL from /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.wasm
    at new Request (node:internal/deps/undici/undici:5423:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6219:25)
    at Object.fetch (node:internal/deps/undici/undici:7053:20)
    at fetch (node:internal/bootstrap/pre_execution:198:25)
    at instantiateAsync (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:424:28)
    at createWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:447:13)
    at /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:1480:19
    at Object.instantiateEmscriptenWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/emscripten-utils.js:15:12)
    at Object.dec (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/codecs.js:171:42)
    at Object.decodeBuffer (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/impl.js:52:31)

Import trace for requested module:
./src/components/Faqs.jsx
./src/pages/index.jsx

./src/images/background-features.jpg
TypeError: Failed to parse URL from /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.wasm
    at new Request (node:internal/deps/undici/undici:5423:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6219:25)
    at Object.fetch (node:internal/deps/undici/undici:7053:20)
    at fetch (node:internal/bootstrap/pre_execution:198:25)
    at instantiateAsync (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:424:28)
    at createWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:447:13)
    at /Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:1480:19
    at Object.instantiateEmscriptenWasm (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/emscripten-utils.js:15:12)
    at Object.dec (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/codecs.js:171:42)
    at Object.decodeBuffer (/Users/robbiemckinstry/workspace/whiterabbittech/salient/node_modules/next/dist/server/lib/squoosh/impl.js:52:31)

Import trace for requested module:
./src/components/PrimaryFeatures.jsx
./src/pages/index.jsx


> Build failed because of webpack errors
```

**Expected behavior**
I expected the build to succeed, creating a static website bundled in an output directory.

**Browser/Device (if applicable)**
 - OS: MacOS 12.4 Monteray

**Comment by bradlc** [comment]
Thanks for reporting, @RobbieMcKinstry. This was caused by a [Next.js issue](https://github.com/vercel/next.js/issues/38020) that has now been resolved. We have bumped all of the templates to the latest version of Next.js. For existing projects upgrading Next.js should fix the issue: `npm install next@latest` – I hope that helps!

**Comment by RobbieMcKinstry** [comment]
Thank you! :)
