### ISSUE TITLE
Syntax Template crashes on `next build && next export`

### ISSUE THREAD

**Issue by knobel-dk** [tailwindlabs/tailwindui-issues#1318]
**What component (if applicable)**
The Syntax Template

**Describe the bug**
When running `next build && next export` in CloudFlare pages, it get this error:
```
2022-09-12T17:34:42.534074Z	Cloning repository...
2022-09-12T17:34:43.921031Z	From https://github.com/XXXXX/XXXXX
2022-09-12T17:34:43.922102Z	 * branch            4b0729b6b3fda6787cd7486bdf7edf3eca2f56e7 -> FETCH_HEAD
2022-09-12T17:34:43.922387Z	
2022-09-12T17:34:43.993215Z	HEAD is now at 4b0729b initial commit
2022-09-12T17:34:43.993836Z	
2022-09-12T17:34:44.144832Z	
2022-09-12T17:34:44.17244Z	Success: Finished cloning repository files
2022-09-12T17:34:44.834457Z	Installing dependencies
2022-09-12T17:34:44.846196Z	Python version set to 2.7
2022-09-12T17:34:48.223329Z	v12.18.0 is already installed.
2022-09-12T17:34:49.419305Z	Now using node v12.18.0 (npm v6.14.4)
2022-09-12T17:34:49.635794Z	Started restoring cached build plugins
2022-09-12T17:34:49.651215Z	Finished restoring cached build plugins
2022-09-12T17:34:50.128636Z	Attempting ruby version 2.7.1, read from environment
2022-09-12T17:34:53.677471Z	Using ruby version 2.7.1
2022-09-12T17:34:54.04436Z	Using PHP version 5.6
2022-09-12T17:34:54.205824Z	5.2 is already installed.
2022-09-12T17:34:54.231781Z	Using Swift version 5.2
2022-09-12T17:34:54.232828Z	Started restoring cached node modules
2022-09-12T17:34:54.247963Z	Finished restoring cached node modules
2022-09-12T17:34:54.488612Z	Installing NPM modules using NPM version 6.14.4
2022-09-12T17:34:55.468176Z	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2022-09-12T17:35:08.206995Z	
2022-09-12T17:35:08.207332Z	> core-js-pure@3.23.2 postinstall /opt/buildhome/repo/node_modules/core-js-pure
2022-09-12T17:35:08.207492Z	> node -e "try{require('./postinstall')}catch(e){}"
2022-09-12T17:35:08.20764Z	
2022-09-12T17:35:08.31185Z	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2022-09-12T17:35:08.312269Z	
2022-09-12T17:35:08.312443Z	[96mThe project needs your help! Please consider supporting of core-js:[0m
2022-09-12T17:35:08.312566Z	[96m>[94m https://opencollective.com/core-js [0m
2022-09-12T17:35:08.312684Z	[96m>[94m https://patreon.com/zloirock [0m
2022-09-12T17:35:08.312795Z	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2022-09-12T17:35:08.312904Z	
2022-09-12T17:35:08.313024Z	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2022-09-12T17:35:08.31316Z	
2022-09-12T17:35:08.679149Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm-eabi@12.3.0 (node_modules/@next/swc-android-arm-eabi):
2022-09-12T17:35:08.679585Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm-eabi@12.3.0: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.679812Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm64@12.3.0 (node_modules/@next/swc-android-arm64):
2022-09-12T17:35:08.68Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm64@12.3.0: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.680198Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@12.3.0 (node_modules/@next/swc-darwin-arm64):
2022-09-12T17:35:08.680351Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@12.3.0: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.680493Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@12.3.0 (node_modules/@next/swc-linux-arm64-gnu):
2022-09-12T17:35:08.68064Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@12.3.0: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.680788Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@12.3.0 (node_modules/@next/swc-win32-arm64-msvc):
2022-09-12T17:35:08.680928Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@12.3.0: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.681286Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@12.3.0 (node_modules/@next/swc-win32-x64-msvc):
2022-09-12T17:35:08.681575Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@12.3.0: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.681738Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm-gnueabihf@12.3.0 (node_modules/@next/swc-linux-arm-gnueabihf):
2022-09-12T17:35:08.682368Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm-gnueabihf@12.3.0: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.682753Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-freebsd-x64@12.3.0 (node_modules/@next/swc-freebsd-x64):
2022-09-12T17:35:08.683137Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-freebsd-x64@12.3.0: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.683305Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@12.3.0 (node_modules/@next/swc-darwin-x64):
2022-09-12T17:35:08.683451Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@12.3.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.683871Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@12.3.0 (node_modules/@next/swc-linux-arm64-musl):
2022-09-12T17:35:08.684071Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@12.3.0: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.68424Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@12.3.0 (node_modules/@next/swc-win32-ia32-msvc):
2022-09-12T17:35:08.684382Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@12.3.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.684838Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2022-09-12T17:35:08.685019Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2022-09-12T17:35:08.685802Z	
2022-09-12T17:35:08.685977Z	added 301 packages from 192 contributors and audited 313 packages in 13.253s
2022-09-12T17:35:08.804261Z	
2022-09-12T17:35:08.804618Z	81 packages are looking for funding
2022-09-12T17:35:08.8048Z	  run `npm fund` for details
2022-09-12T17:35:08.804952Z	
2022-09-12T17:35:08.805105Z	found 0 vulnerabilities
2022-09-12T17:35:08.805248Z	
2022-09-12T17:35:08.823584Z	NPM modules installed
2022-09-12T17:35:09.227896Z	Installing Hugo 0.54.0
2022-09-12T17:35:09.937895Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-09-12T17:35:09.942893Z	Started restoring cached go cache
2022-09-12T17:35:09.967457Z	Finished restoring cached go cache
2022-09-12T17:35:10.131014Z	go version go1.14.4 linux/amd64
2022-09-12T17:35:10.147496Z	go version go1.14.4 linux/amd64
2022-09-12T17:35:10.150507Z	Installing missing commands
2022-09-12T17:35:10.150831Z	Verify run directory
2022-09-12T17:35:10.151127Z	Executing user command: next build && next export
2022-09-12T17:35:10.716344Z	warn  - You have enabled experimental features (newNextLinkBehavior, scrollRestoration) in next.config.js.
2022-09-12T17:35:10.716701Z	warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
2022-09-12T17:35:10.716863Z	
2022-09-12T17:35:10.718769Z	(node:1342) ExperimentalWarning: The ESM module loader is experimental.
2022-09-12T17:35:10.723598Z	warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2022-09-12T17:35:10.76265Z	Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-09-12T17:35:10.762979Z	This information is used to shape Next.js' roadmap and prioritize features.
2022-09-12T17:35:10.763162Z	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2022-09-12T17:35:10.763293Z	https://nextjs.org/telemetry
2022-09-12T17:35:10.763408Z	
2022-09-12T17:35:10.90594Z	info  - Linting and checking validity of types...
2022-09-12T17:35:13.383266Z	info  - Creating an optimized production build...
2022-09-12T17:35:18.500362Z	Failed to compile.
2022-09-12T17:35:18.500697Z	
2022-09-12T17:35:18.500874Z	./src/pages/docs/architecture-guide.md
2022-09-12T17:35:18.501004Z	/opt/buildhome/repo/node_modules/@markdoc/markdoc/dist/index.js:6635
2022-09-12T17:35:18.50113Z	  return !!value?.$$mdtype;
2022-09-12T17:35:18.501247Z	                 ^
2022-09-12T17:35:18.501354Z	
2022-09-12T17:35:18.50146Z	SyntaxError: Unexpected token '.'
2022-09-12T17:35:18.501603Z	    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
2022-09-12T17:35:18.501719Z	    at Module._compile (internal/modules/cjs/loader.js:1102:27)
2022-09-12T17:35:18.501826Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.501943Z	    at Module.load (internal/modules/cjs/loader.js:986:32)
2022-09-12T17:35:18.50205Z	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2022-09-12T17:35:18.502198Z	    at Module.require (internal/modules/cjs/loader.js:1026:19)
2022-09-12T17:35:18.502317Z	    at require (internal/modules/cjs/helpers.js:72:18)
2022-09-12T17:35:18.502427Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/@markdoc/next.js/src/loader.js:3:17)
2022-09-12T17:35:18.502539Z	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
2022-09-12T17:35:18.502647Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.502755Z	
2022-09-12T17:35:18.502871Z	./src/pages/docs/basics-of-time-travel.md
2022-09-12T17:35:18.50298Z	/opt/buildhome/repo/node_modules/@markdoc/markdoc/dist/index.js:6635
2022-09-12T17:35:18.503086Z	  return !!value?.$$mdtype;
2022-09-12T17:35:18.503213Z	                 ^
2022-09-12T17:35:18.503326Z	
2022-09-12T17:35:18.503441Z	SyntaxError: Unexpected token '.'
2022-09-12T17:35:18.50355Z	    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
2022-09-12T17:35:18.503657Z	    at Module._compile (internal/modules/cjs/loader.js:1102:27)
2022-09-12T17:35:18.503766Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.503888Z	    at Module.load (internal/modules/cjs/loader.js:986:32)
2022-09-12T17:35:18.504002Z	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2022-09-12T17:35:18.504112Z	    at Module.require (internal/modules/cjs/loader.js:1026:19)
2022-09-12T17:35:18.504251Z	    at require (internal/modules/cjs/helpers.js:72:18)
2022-09-12T17:35:18.504371Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/@markdoc/next.js/src/loader.js:3:17)
2022-09-12T17:35:18.504493Z	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
2022-09-12T17:35:18.50461Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.504815Z	
2022-09-12T17:35:18.505053Z	./src/pages/docs/cacheadvance-flush.md
2022-09-12T17:35:18.505198Z	/opt/buildhome/repo/node_modules/@markdoc/markdoc/dist/index.js:6635
2022-09-12T17:35:18.505312Z	  return !!value?.$$mdtype;
2022-09-12T17:35:18.505434Z	                 ^
2022-09-12T17:35:18.505599Z	
2022-09-12T17:35:18.505716Z	SyntaxError: Unexpected token '.'
2022-09-12T17:35:18.505831Z	    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
2022-09-12T17:35:18.505949Z	    at Module._compile (internal/modules/cjs/loader.js:1102:27)
2022-09-12T17:35:18.506079Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.506205Z	    at Module.load (internal/modules/cjs/loader.js:986:32)
2022-09-12T17:35:18.506319Z	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2022-09-12T17:35:18.506426Z	    at Module.require (internal/modules/cjs/loader.js:1026:19)
2022-09-12T17:35:18.506533Z	    at require (internal/modules/cjs/helpers.js:72:18)
2022-09-12T17:35:18.506638Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/@markdoc/next.js/src/loader.js:3:17)
2022-09-12T17:35:18.506755Z	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
2022-09-12T17:35:18.506869Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.506993Z	
2022-09-12T17:35:18.507112Z	./src/pages/docs/cacheadvance-predict.md
2022-09-12T17:35:18.507235Z	/opt/buildhome/repo/node_modules/@markdoc/markdoc/dist/index.js:6635
2022-09-12T17:35:18.507393Z	  return !!value?.$$mdtype;
2022-09-12T17:35:18.50753Z	                 ^
2022-09-12T17:35:18.507643Z	
2022-09-12T17:35:18.507773Z	SyntaxError: Unexpected token '.'
2022-09-12T17:35:18.507895Z	    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
2022-09-12T17:35:18.508004Z	    at Module._compile (internal/modules/cjs/loader.js:1102:27)
2022-09-12T17:35:18.508109Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.508239Z	    at Module.load (internal/modules/cjs/loader.js:986:32)
2022-09-12T17:35:18.508347Z	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2022-09-12T17:35:18.508454Z	    at Module.require (internal/modules/cjs/loader.js:1026:19)
2022-09-12T17:35:18.508562Z	    at require (internal/modules/cjs/helpers.js:72:18)
2022-09-12T17:35:18.508666Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/@markdoc/next.js/src/loader.js:3:17)
2022-09-12T17:35:18.508787Z	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
2022-09-12T17:35:18.508905Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.509012Z	
2022-09-12T17:35:18.509129Z	./src/pages/docs/cacheadvance-regret.md
2022-09-12T17:35:18.509239Z	/opt/buildhome/repo/node_modules/@markdoc/markdoc/dist/index.js:6635
2022-09-12T17:35:18.509344Z	  return !!value?.$$mdtype;
2022-09-12T17:35:18.50945Z	                 ^
2022-09-12T17:35:18.509555Z	
2022-09-12T17:35:18.509661Z	SyntaxError: Unexpected token '.'
2022-09-12T17:35:18.509767Z	    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
2022-09-12T17:35:18.509893Z	    at Module._compile (internal/modules/cjs/loader.js:1102:27)
2022-09-12T17:35:18.510006Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.510114Z	    at Module.load (internal/modules/cjs/loader.js:986:32)
2022-09-12T17:35:18.510234Z	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2022-09-12T17:35:18.510348Z	    at Module.require (internal/modules/cjs/loader.js:1026:19)
2022-09-12T17:35:18.510474Z	    at require (internal/modules/cjs/helpers.js:72:18)
2022-09-12T17:35:18.510583Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/@markdoc/next.js/src/loader.js:3:17)
2022-09-12T17:35:18.510692Z	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
2022-09-12T17:35:18.510807Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2022-09-12T17:35:18.510926Z	
2022-09-12T17:35:18.511115Z	
2022-09-12T17:35:18.511334Z	> Build failed because of webpack errors
2022-09-12T17:35:18.539793Z	Failed: build command exited with code: 1
2022-09-12T17:35:19.894625Z	Failed: an internal error occurred
```

**To Reproduce**
1. Download the Syntax template
2. Without changing anything, upload it to GitHub repo.
3. Deploy the GitHub repo to cloudflare pages with [this](https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/) guide.
4. See error as it appears in the build log (see above).

**Expected behavior**
I would expect the build/deploy to complete.

**Comment by thecrypticace** [comment]
This looks like it's using Node v12 and the markdoc package requires Node v14 or later. I'm surprised that CF pages doesn't detect this and complain. Set your `NODE_VERSION` env var in Cloudflare pages to `14.20.0`, `16.17.0`, or `18.9.0` at try deploying again.

**Comment by knobel-dk** [comment]
Thanks @thecrypticace.

For anyone reading along here, there are two more things worth noting:
1. Cloudflare Pages does not support 18.9.0 so I set `NODE_VERSION=16.17.0`
2. You cannot do `next export` with the default image optimizer so I set `images: {unoptimized: true,},` in `next.config.mjs`
