### ISSUE TITLE
Error `NextRouter was not mounted` in TailwindUI Spotlight Theme with NextJS 13.2

### ISSUE THREAD

**Issue by ringods** [tailwindlabs/tailwindui-issues#1433]
**What component (if applicable)**
- URL for category: 
- Component name: `Header.jsx` and `ArticleLayout.jsx`

**Describe the bug**

I started from the Spotlight Theme and [upgraded to Next 13.2](https://beta.nextjs.org/docs/upgrade-guide). When running `npm run build`, I got this error:

```
next build

warn  - You have enabled experimental feature (scrollRestoration) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Linting and checking validity of types  
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
info  - Compiled successfully
info  - Collecting page data  
info  - Creating an optimized production build ..
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at useRouter (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/next/dist/client/router.js:122:15)
    at ArticleLayout (/Users/ringods/Projects/personal/ringo_de_smet_name/.next/server/chunks/295.js:61:39)
    at Fb (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:65:44)
    at Ib (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)
    at W (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
    at Ib (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
    at W (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
    at Ib (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:482)
    at W (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
    at Eb (/Users/ringods/Projects/personal/ringo_de_smet_name/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:82:216)
info  - Generating static pages (12/12)
```

**To Reproduce**
1. Follow the [Upgrade Guide](https://beta.nextjs.org/docs/upgrade-guide) to bump to Next 13.2
1. Run `npm run build` on the Spotlight Theme
1. See error

**Expected behavior**

Build should work.

**Browser/Device (if applicable)**
 - OS: macOS 13.2.1 with Node 18.5.1
 - Browser Firefox 111.0

**Additional context**

When changing from the `pages` based to the new App Router, the use of `useRouter` should be updated. See the [migrating instructions](https://beta.nextjs.org/docs/api-reference/use-router). For backwards compatibility, changing:

```ts
import { useRouter } from 'next/router'
```

to

```ts
import { useRouter } from 'next/compat/router'
```

solved it in the meantime for the `pages` router.

https://github.com/vercel/next.js/blob/4240dcc410b441807a33a87191a3413d3dc4564b/packages/next/client/compat/router.ts

**Comment by thecrypticace** [comment]
Hey! So it took a bit but I was able to track this down!

A change in Next.js 13.2 causes the default `useRouter` hook to throw when a router isn't mounted. This only happens when rendering a component containing `useRouter()` outside the context of Next.js which happens when the RSS feed is generated during a production build. Previously, the `useRouter` hook returned `null` instead of throwing, which is why this wasn't an issue for the RSS feed before.

I've updated the template on tailwindui.com to fix this. Feel free to download it again or, you can apply two changes fix the build error.

In the `src/lib/generateRssFeed.js` file make the following changes:

1. Import `withRouter` from `next/router`:
```diff
  import ReactDOMServer from 'react-dom/server'
  import { Feed } from 'feed'
  import { mkdir, writeFile } from 'fs/promises'
+ import { withRouter } from 'next/router'
```

2. Wrap the RSS feed component in a Router instance:
```diff
  let html = ReactDOMServer.renderToStaticMarkup(
-   <article.component isRssFeed />
+   withRouter(<article.component isRssFeed />)
  )
```

With this the build will now work. Thanks for taking the time to report this bug! ✨
